#!/usr/bin/env node
/**
 * invalidate_auto_tags.js — Delete all auto-generated CarTag rows
 *
 * Run AFTER deploying the autotag v3 code changes, so stale auto-tags
 * (generated by the old division+drivetrain logic) are removed and the v3
 * logic takes over.
 *
 * Before running against production:
 *   - Take a Neon restore point first.
 *   - Use the direct (unpooled) connection string for the transaction,
 *     consistent with the project's one-off data-script convention.
 *   - This only deletes source = 'auto' rows. source = 'user' tags and all
 *     UserGarage rows are never touched.
 *   - After this runs, regenerate auto-tags with `tsx scripts/backfillAutoTags.ts`
 *     (it now passes car stats, so the regenerated tags are full v3). Race-type
 *     labels recompute fresh on render regardless; this repopulates the stored
 *     auto-tag chips used for display and tag filtering.
 *
 * Usage:
 *   DATABASE_URL=<direct_url> node prisma/invalidate_auto_tags.js
 *
 * NOT a schema migration — do not place this in prisma/migrations/.
 */
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  console.log('Counting stale auto-tags...')
  const count = await prisma.carTag.count({ where: { source: 'auto' } })
  console.log(`Found ${count} auto-tag rows to delete.`)
  if (count === 0) {
    console.log('Nothing to do.')
    return
  }

  const result = await prisma.carTag.deleteMany({ where: { source: 'auto' } })
  console.log('\n──────────────────────────────────────────')
  console.log(`Deleted: ${result.count} auto-tag rows`)
  console.log('User tags (source: "user"): untouched')
  console.log('──────────────────────────────────────────')
  console.log('Regenerate with: tsx scripts/backfillAutoTags.ts')
}

main()
  .catch((e) => {
    console.error('Fatal:', e.message ?? e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
